#pragma once
// GENERATED by proto/gen/gen_cpp.py from espdisp-control-1.schema.json — do not edit.
#include <ArduinoJson.h>
#include <string.h>
namespace proto {
constexpr int kProtoMajor = 2;
constexpr int kProtoMinor = 0;

struct ViewRef;
struct Session;
struct DeviceRecord;
struct Attach;
struct AttachAck;
struct Switch;
struct SwitchAck;
struct Heartbeat;
struct HeartbeatAck;
struct Detach;
struct ControlState;

struct ViewRef {
    char id[48] = {0};
    char title[48] = {0};
};

struct Session {
    char controllerId[48] = {0};
    char name[48] = {0};
    char color[48] = {0};
    long lastSeen = {};
};

struct DeviceRecord {
    char v[48] = {0};
    char deviceId[48] = {0};
    char name[48] = {0};
    char role[48] = {0};
    char board[48] = {0};
    char display[48] = {0};
    char currentView[48] = {0};
    ViewRef views[16] = {};
    int views_count = 0;
    char transports[16][24] = {};
    int transports_count = 0;
    bool authRequired = {};
};

struct Attach {
    char v[48] = {0};
    char t[48] = {0};
    char controllerId[48] = {0};
    char name[48] = {0};
    char color[48] = {0};
    char key[48] = {0};
    long ttlMs = {};
};

struct AttachAck {
    char v[48] = {0};
    char t[48] = {0};
    bool accepted = {};
    char sessionId[48] = {0};
    long ttlMs = {};
    char reason[48] = {0};
    DeviceRecord device = {};
};

struct Switch {
    char v[48] = {0};
    char t[48] = {0};
    char sessionId[48] = {0};
    char viewId[48] = {0};
};

struct SwitchAck {
    char v[48] = {0};
    char t[48] = {0};
    bool ok = {};
    char currentView[48] = {0};
    char reason[48] = {0};
};

struct Heartbeat {
    char v[48] = {0};
    char t[48] = {0};
    char sessionId[48] = {0};
};

struct HeartbeatAck {
    char v[48] = {0};
    char t[48] = {0};
    bool ok = {};
    long ttlMs = {};
};

struct Detach {
    char v[48] = {0};
    char t[48] = {0};
    char sessionId[48] = {0};
};

struct ControlState {
    char v[48] = {0};
    char t[48] = {0};
    char currentView[48] = {0};
    Session sessions[16] = {};
    int sessions_count = 0;
};

inline void from_json(JsonObjectConst o, ViewRef &s) {
    strncpy(s.id, o["id"] | "", sizeof(s.id) - 1);
    strncpy(s.title, o["title"] | "", sizeof(s.title) - 1);
}
inline void to_json(JsonObject o, const ViewRef &s) {
    o["id"] = s.id;
    o["title"] = s.title;
}

inline void from_json(JsonObjectConst o, Session &s) {
    strncpy(s.controllerId, o["controllerId"] | "", sizeof(s.controllerId) - 1);
    strncpy(s.name, o["name"] | "", sizeof(s.name) - 1);
    strncpy(s.color, o["color"] | "", sizeof(s.color) - 1);
    s.lastSeen = o["lastSeen"] | 0L;
}
inline void to_json(JsonObject o, const Session &s) {
    o["controllerId"] = s.controllerId;
    o["name"] = s.name;
    o["color"] = s.color;
    o["lastSeen"] = s.lastSeen;
}

inline void from_json(JsonObjectConst o, DeviceRecord &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.deviceId, o["deviceId"] | "", sizeof(s.deviceId) - 1);
    strncpy(s.name, o["name"] | "", sizeof(s.name) - 1);
    strncpy(s.role, o["role"] | "", sizeof(s.role) - 1);
    strncpy(s.board, o["board"] | "", sizeof(s.board) - 1);
    strncpy(s.display, o["display"] | "", sizeof(s.display) - 1);
    strncpy(s.currentView, o["currentView"] | "", sizeof(s.currentView) - 1);
    {
        JsonArrayConst a = o["views"].as<JsonArrayConst>();
        s.views_count = 0;
        for (JsonVariantConst e : a) {
            if (s.views_count >= 16) break;
            from_json(e.as<JsonObjectConst>(), s.views[s.views_count]);
            s.views_count++;
        }
    }
    {
        JsonArrayConst a = o["transports"].as<JsonArrayConst>();
        s.transports_count = 0;
        for (JsonVariantConst e : a) {
            if (s.transports_count >= 16) break;
            strncpy(s.transports[s.transports_count], e | "", 23);
            s.transports_count++;
        }
    }
    s.authRequired = o["authRequired"] | false;
}
inline void to_json(JsonObject o, const DeviceRecord &s) {
    o["v"] = s.v;
    o["deviceId"] = s.deviceId;
    o["name"] = s.name;
    o["role"] = s.role;
    o["board"] = s.board;
    o["display"] = s.display;
    o["currentView"] = s.currentView;
    {
        JsonArray a = o["views"].to<JsonArray>();
        for (int i = 0; i < s.views_count; i++) {
            JsonObject e = a.add<JsonObject>();
            to_json(e, s.views[i]);
        }
    }
    {
        JsonArray a = o["transports"].to<JsonArray>();
        for (int i = 0; i < s.transports_count; i++) {
            a.add(s.transports[i]);
        }
    }
    o["authRequired"] = s.authRequired;
}

inline void from_json(JsonObjectConst o, Attach &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    strncpy(s.controllerId, o["controllerId"] | "", sizeof(s.controllerId) - 1);
    strncpy(s.name, o["name"] | "", sizeof(s.name) - 1);
    strncpy(s.color, o["color"] | "", sizeof(s.color) - 1);
    strncpy(s.key, o["key"] | "", sizeof(s.key) - 1);
    s.ttlMs = o["ttlMs"] | 0L;
}
inline void to_json(JsonObject o, const Attach &s) {
    o["v"] = s.v;
    o["t"] = "attach";
    o["controllerId"] = s.controllerId;
    o["name"] = s.name;
    o["color"] = s.color;
    o["key"] = s.key;
    o["ttlMs"] = s.ttlMs;
}

inline void from_json(JsonObjectConst o, AttachAck &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    s.accepted = o["accepted"] | false;
    strncpy(s.sessionId, o["sessionId"] | "", sizeof(s.sessionId) - 1);
    s.ttlMs = o["ttlMs"] | 0L;
    strncpy(s.reason, o["reason"] | "", sizeof(s.reason) - 1);
    if (o["device"].is<JsonObjectConst>()) from_json(o["device"].as<JsonObjectConst>(), s.device);
}
inline void to_json(JsonObject o, const AttachAck &s) {
    o["v"] = s.v;
    o["t"] = "attachAck";
    o["accepted"] = s.accepted;
    o["sessionId"] = s.sessionId;
    o["ttlMs"] = s.ttlMs;
    o["reason"] = s.reason;
    {
        JsonObject e = o["device"].to<JsonObject>();
        to_json(e, s.device);
    }
}

inline void from_json(JsonObjectConst o, Switch &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    strncpy(s.sessionId, o["sessionId"] | "", sizeof(s.sessionId) - 1);
    strncpy(s.viewId, o["viewId"] | "", sizeof(s.viewId) - 1);
}
inline void to_json(JsonObject o, const Switch &s) {
    o["v"] = s.v;
    o["t"] = "switch";
    o["sessionId"] = s.sessionId;
    o["viewId"] = s.viewId;
}

inline void from_json(JsonObjectConst o, SwitchAck &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    s.ok = o["ok"] | false;
    strncpy(s.currentView, o["currentView"] | "", sizeof(s.currentView) - 1);
    strncpy(s.reason, o["reason"] | "", sizeof(s.reason) - 1);
}
inline void to_json(JsonObject o, const SwitchAck &s) {
    o["v"] = s.v;
    o["t"] = "switchAck";
    o["ok"] = s.ok;
    o["currentView"] = s.currentView;
    o["reason"] = s.reason;
}

inline void from_json(JsonObjectConst o, Heartbeat &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    strncpy(s.sessionId, o["sessionId"] | "", sizeof(s.sessionId) - 1);
}
inline void to_json(JsonObject o, const Heartbeat &s) {
    o["v"] = s.v;
    o["t"] = "heartbeat";
    o["sessionId"] = s.sessionId;
}

inline void from_json(JsonObjectConst o, HeartbeatAck &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    s.ok = o["ok"] | false;
    s.ttlMs = o["ttlMs"] | 0L;
}
inline void to_json(JsonObject o, const HeartbeatAck &s) {
    o["v"] = s.v;
    o["t"] = "heartbeatAck";
    o["ok"] = s.ok;
    o["ttlMs"] = s.ttlMs;
}

inline void from_json(JsonObjectConst o, Detach &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    strncpy(s.sessionId, o["sessionId"] | "", sizeof(s.sessionId) - 1);
}
inline void to_json(JsonObject o, const Detach &s) {
    o["v"] = s.v;
    o["t"] = "detach";
    o["sessionId"] = s.sessionId;
}

inline void from_json(JsonObjectConst o, ControlState &s) {
    strncpy(s.v, o["v"] | "", sizeof(s.v) - 1);
    strncpy(s.t, o["t"] | "", sizeof(s.t) - 1);
    strncpy(s.currentView, o["currentView"] | "", sizeof(s.currentView) - 1);
    {
        JsonArrayConst a = o["sessions"].as<JsonArrayConst>();
        s.sessions_count = 0;
        for (JsonVariantConst e : a) {
            if (s.sessions_count >= 16) break;
            from_json(e.as<JsonObjectConst>(), s.sessions[s.sessions_count]);
            s.sessions_count++;
        }
    }
}
inline void to_json(JsonObject o, const ControlState &s) {
    o["v"] = s.v;
    o["t"] = "controlState";
    o["currentView"] = s.currentView;
    {
        JsonArray a = o["sessions"].to<JsonArray>();
        for (int i = 0; i < s.sessions_count; i++) {
            JsonObject e = a.add<JsonObject>();
            to_json(e, s.sessions[i]);
        }
    }
}

}  // namespace proto
